// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LgucFfJVSHdLIM3xw-IjpYB4d1OyNNk',
    appId: '1:131963849817:web:f3db20aa160bbcf5743548',
    messagingSenderId: '131963849817',
    projectId: 'vitalfiapps',
    authDomain: 'vitalfiapps.firebaseapp.com',
    storageBucket: 'vitalfiapps.firebasestorage.app',
    measurementId: 'G-6GDR47HW22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZY8hw5ebyKQ4g9AFagGyKfzWsqSf4tYM',
    appId: '1:131963849817:android:7f1a3a9873ea735c743548',
    messagingSenderId: '131963849817',
    projectId: 'vitalfiapps',
    storageBucket: 'vitalfiapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbomO2YXQjRTbV7SWgeGQNYR2M-1fvEqU',
    appId: '1:131963849817:ios:7ece70e2873f88a2743548',
    messagingSenderId: '131963849817',
    projectId: 'vitalfiapps',
    storageBucket: 'vitalfiapps.firebasestorage.app',
    iosBundleId: 'com.application.vitalfiapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbomO2YXQjRTbV7SWgeGQNYR2M-1fvEqU',
    appId: '1:131963849817:ios:7ece70e2873f88a2743548',
    messagingSenderId: '131963849817',
    projectId: 'vitalfiapps',
    storageBucket: 'vitalfiapps.firebasestorage.app',
    iosBundleId: 'com.application.vitalfiapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-LgucFfJVSHdLIM3xw-IjpYB4d1OyNNk',
    appId: '1:131963849817:web:f3c5161735c90f82743548',
    messagingSenderId: '131963849817',
    projectId: 'vitalfiapps',
    authDomain: 'vitalfiapps.firebaseapp.com',
    storageBucket: 'vitalfiapps.firebasestorage.app',
    measurementId: 'G-71J4L6PSBL',
  );
}
